sudo: required

language: python
python:
  - "2.7"

before_install:
  - bash travis/install-build-deps.sh
  - bash travis/install-pytest.sh

install:
  - unset PYTHON_CFLAGS
  - ./autogen.sh
  - ./configure
  - env
  - make

script:
  - sudo sysctl kernel.yama.ptrace_scope=0
  - py.test tests/
